import { listSlots } from './slots.js';

function block(name, profile) {
  const lines = [];
  lines.push(`workspace "${name}" {`);
  lines.push('    layout {');
  lines.push('        focus-ring {');
  lines.push(`            active-color "${profile.ring}"`);
  lines.push('        }');
  if (profile.border) {
    lines.push('        border {');
    lines.push('            on');
    lines.push(`            active-color "${profile.border}"`);
    lines.push('        }');
  }
  lines.push('    }');
  lines.push('}');
  return lines.join('\n');
}

export function generateKdl(catalog) {
  const header = '// Generated by wsprofiled from profiles.yaml. Do not edit by hand.\n';
  const blocks = [];
  for (const profile of catalog.profiles) {
    for (const { name } of listSlots(profile)) {
      blocks.push(block(name, profile));
    }
  }
  return header + blocks.join('\n\n') + '\n';
}
