$primary = rgb(b4d269)
$surface = rgb(13140f)
$secondary = rgb(c3caaa)
$error = rgb(ffb4ab)
$tertiary = rgb(a1d0c7)
$surface_lowest = rgb(0e0f0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
