color0 #121416
color1 #ffb4ab
color2 #95ccff
color3 #b9c8da
color4 #d2bfe6
color5 #95ccff
color6 #b9c8da
color7 #e2e2e5
color8 #8c9198
color9 #ffb4ab
color10 #95ccff
color11 #b9c8da
color12 #d2bfe6
color13 #95ccff
color14 #b9c8da
color15 #e2e2e5

cursor                #e2e2e5
cursor_text_color     #121416
background            #121416
foreground            #e2e2e5
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #95ccff
inactive_border_color #42474e
url_color             #95ccff
