terminal.apps:
  - kitty
  - com.mitchellh.ghostty
glass.attenuationColor: "#111317"
glass.chromaticAberration: 0.46
glass.distortion: 0.16
glass.distortionScale: 0.02
glass.jellyFlex: 0.018
glass.jellyRipple: 0.48
glass.paneLip: 10
glass.thickness: 26.3
glass.anisotropicBlur: 0.05
glass.attenuationDistance: 30
glass.paneShiftX: -5
glass.inactive.chromaticAberration: 0.38
glass.inactive.noise: 0.03
compositor.gaps: 38
glass.ior: 1.2
glass.inactive.roughness: 0
glass.roughness: 0.55
glass.paneShiftY: 3
glass.inactive.saturation: 1
glass.inactive.distortion: 0.24
