#!/bin/sh
# loaded by GDM

# laptop monitor connection
#external=$(xrandr -q | awk '/HDMI1/ {print $2}')

#if [ "$external" = "connected" ]; then
#    xrandr --output HDMI1 --auto --same-as eDP1
#    xrandr --output eDP1 --off
#fi

# compositing
# compton -cGb

# enable restart X
setxkbmap -option terminate:ctrl_alt_bksp

# map caps lock to escape
if [ -s ~/.xmodmaprc ]; then
    xmodmap ~/.xmodmaprc
fi


