compositor.gaps: 6
glass.attenuationDistance: 18
glass.backdropBlur: true
glass.attenuationColor: "#222B29"
glass.thickness: 41.7
glass.ior: 1.12
glass.chromaticAberration: 0.5
glass.distortion: 0.42
glass.distortionScale: 0.02
glass.anisotropicBlur: 0.05
glass.roughness: 0
glass.paneLip: 10
glass.paneShiftX: -5
glass.paneShiftY: 5
glass.jellyFlex: 0.018
glass.jellyRipple: 0.48
glass.noiseType: white
glass.inactive.chromaticAberration: 0.42
glass.inactive.roughness: 0
glass.inactive.distortion: 0.14
glass.inactive.attenuationDistance: 73
glass.inactive.noise: 0.06
glass.inactive.saturation: 0.5
glass.inactive.anisotropicBlur: 0.09
