--color=dark
--color=fg:{{colors.on_surface.default.hex}},bg:-1,hl:{{colors.tertiary.default.hex}},fg+:{{colors.on_primary.default.hex}},bg+:{{colors.primary.default.hex}},hl+:{{colors.tertiary_fixed_dim.default.hex}}
--color=info:{{colors.secondary.default.hex}},prompt:{{colors.primary.default.hex}},pointer:{{colors.error.default.hex}},marker:{{colors.tertiary.default.hex}},spinner:{{colors.primary.default.hex}},header:{{colors.primary.default.hex}}
