# for debugging...
# set -x

# Check to see if zprofile has been loaded yet
if [[ $ZPROFILE_LOADED = true ]]; then
    return
fi

source /cbcb/sw/cbcb_profile

# CBCB Modules
export MODULEPATH="$MODULEPATH:/cbcb/sw/RedHat-7-x86_64/common/modules/version/dev"
export CBCB_DEV="/cbcb/sw/RedHat-7-x86_64/dev"

# Load modules
module add         \
    zsh/5.3.1      \
    R/3.5.1

# Exports
export ZPROFILE_LOADED='true'
