# host-titan.conf — titan (desktop, 4K, NVIDIA GPU)

# GPU: NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# 4K: generous spacing
general {
    gaps_in = 5
    gaps_out = 10
}

decoration {
    rounding = 20
    blur {
        enabled = true
        size = 8
        passes = 2
        vibrancy = 0.1696
    }
}
