profiles:
  - id: ember
    label: "Ember - client-api"
    instances: 1
    ring: "#ff7a45"
    border: "#ff7a45"
    icon: ""
    theme:
      wallpaper: ~/d/linux/backgrounds/3440/PXL_20210602_024124219.jpg
      mode: dark
  - id: tide
    label: "Tide - infra"
    instances: 2
    ring: "#3aa6ff"
    icon: ""
    theme:
      wallpaper: ~/d/linux/backgrounds/3440/PXL_20210603_114137918.jpg
      mode: dark
