color0 #121316
color1 #ffb4ab
color2 #9fcaff
color3 #bbc7db
color4 #d7bee4
color5 #9fcaff
color6 #bbc7db
color7 #e2e2e6
color8 #8d9199
color9 #ffb4ab
color10 #9fcaff
color11 #bbc7db
color12 #d7bee4
color13 #9fcaff
color14 #bbc7db
color15 #e2e2e6

cursor                #e2e2e6
cursor_text_color     #121316
background            #121316
foreground            #e2e2e6
selection_foreground  #c3c6cf
selection_background  #43474e
active_border_color   #9fcaff
inactive_border_color #43474e
url_color             #9fcaff
