color0 #13140f
color1 #ffb4ab
color2 #b4d269
color3 #c3caaa
color4 #a1d0c7
color5 #b4d269
color6 #c3caaa
color7 #e4e3db
color8 #909284
color9 #ffb4ab
color10 #b4d269
color11 #c3caaa
color12 #a1d0c7
color13 #b4d269
color14 #c3caaa
color15 #e4e3db

cursor                #e4e3db
cursor_text_color     #13140f
background            #13140f
foreground            #e4e3db
selection_foreground  #c6c8b8
selection_background  #45483c
active_border_color   #b4d269
inactive_border_color #45483c
url_color             #b4d269
