color0 #121316
color1 #ffb4ab
color2 #a4c9ff
color3 #bcc7db
color4 #d9bde3
color5 #a4c9ff
color6 #bcc7db
color7 #e3e2e6
color8 #8d9199
color9 #ffb4ab
color10 #a4c9ff
color11 #bcc7db
color12 #d9bde3
color13 #a4c9ff
color14 #bcc7db
color15 #e3e2e6

cursor                #e3e2e6
cursor_text_color     #121316
background            #121316
foreground            #e3e2e6
selection_foreground  #c3c6cf
selection_background  #43474e
active_border_color   #a4c9ff
inactive_border_color #43474e
url_color             #a4c9ff
