#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
based on: https://docs.gimp.org/3.0/en/gimp-using-python-plug-in-tutorial.html
"""
import sys

import gi
gi.require_version('Gimp', '3.0')
from gi.repository import Gimp
gi.require_version('GimpUi', '3.0')
from gi.repository import GimpUi
from gi.repository import GLib

class Wet1 (Gimp.PlugIn):
    def do_query_procedures(self):
        return [ "wet-1" ]

    def do_set_i18n (self, name):
        return False

    def do_create_procedure(self, name):
        procedure = Gimp.ImageProcedure.new(self, name,
                                            Gimp.PDBProcType.PLUGIN,
                                            self.run, None)

        procedure.set_image_types("*")

        procedure.set_menu_label("_ wet 1")
        procedure.add_menu_path('<Image>/Filters/_user')

        procedure.set_documentation("..",
                                    "..",
                                    name)
        procedure.set_attribution("keith", "keith", "2025")

        return procedure

    def run(self, procedure, run_mode, image, drawables, config, run_data):
        Gimp.message("Hello world!")
        # do what you want to do, then, in case of success, return:
        return procedure.new_return_values(Gimp.PDBStatusType.SUCCESS, GLib.Error())

Gimp.main(Wet1.__gtype__, sys.argv)
