color0 #16130e
color1 #ffb4ab
color2 #f2bf48
color3 #d8c4a0
color4 #b0cfaa
color5 #f2bf48
color6 #d8c4a0
color7 #e9e1d8
color8 #998f80
color9 #ffb4ab
color10 #f2bf48
color11 #d8c4a0
color12 #b0cfaa
color13 #f2bf48
color14 #d8c4a0
color15 #e9e1d8

cursor                #e9e1d8
cursor_text_color     #16130e
background            #16130e
foreground            #e9e1d8
selection_foreground  #d0c5b4
selection_background  #4d4639
active_border_color   #f2bf48
inactive_border_color #4d4639
url_color             #f2bf48
